name: SonarQube Analysis

on:
  push:
    branches:
      - main

permissions:
  contents: none
  issues: none
  pull-requests: none

env:
  GO_VERSION: 1.26

jobs:
  generate-coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Install Task
        uses: go-task/setup-task@70f2430ad412f838533de8c0515c749ffb2b8bd3 # v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run test
        run: task test
      - name: Merge coverage files
        run: |
          cat proofwatch/coverage.out > coverage.out
          tail -n +2 truthbeam/coverage.out >> coverage.out
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: coverage.out

  sonarqube:
    name: SonarCloud Analysis
    permissions:
      contents: read
      pull-requests: read
    needs: generate-coverage
    uses: complytime/org-infra/.github/workflows/reusable_sonarqube.yml@cfd981e757253218aefb37c91969c32827e5c4b1 # v0.2.1
    with:
      sonar_organization: ${{ vars.SONAR_ORGANIZATION }}
      sonar_project_key: ${{ vars.SONAR_PROJECT_KEY }}
      coverage_artifact_name: coverage
      coverage_file_path: coverage.out
      language_scanner_property: sonar.go.coverage.reportPaths
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      source_token: ${{ secrets.GITHUB_TOKEN }}
